language: python
python:
  - 3.7
before_install:
  - bash write_pip_config.sh
install:
  - pip install -r dev-requirements.txt
script:
  - invoke test
deploy:
  - provider: script
    script:
      bash docker.sh update_image
      invoke update-job-configs
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(dev)$
  - provider: script
    script:
      invoke deploy-jobs
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(dev|stage|main)$
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: [secure]
    # ARTIFACTORY_PASSWORD
    - secure: [secure]
